name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2  # Updated to v2 for Node.js 18.x support
        with:
          node-version: '18.13'  # Updated Node.js version
      - run: npm install
      - run: npm install -g @angular/cli > /dev/null
      - run: ng build --prod
